<form action="editBlog" method="POST">
    <div class="container m-5 p-5">
        <div class="form-group">
            <label>Id</label>
            <input type="text" class="form-control" name="u_id" value="<?php echo $id; ?>" placeholder="Enter email" disabled>
        </div>
        <div class="form-group">
            <label>Title</label>
            <input type="text" class="form-control" name="u_title" value="<?php echo $title; ?>" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label>File</label>
            <input type="file" name="u_file" class="form-control">
        </div>
        <div class="form-group">
            <label>Content</label>
            <textarea class="form-control" name="u_content"><?php echo $content; ?></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>