<?php
if (count($value) > 0) {
    echo '<div class="container px-4 px-lg-5 mt-5" id="main">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 ">';
    foreach ($value as $blog) {
        echo '<div class="col mb-5" >
    <div class="card" style="width: 15rem;">
    <img class="card-img-top" src="https://media.istockphoto.com/photos/blog-light-bulb-sign-picture-id1331943301?b=1&k=20&m=1331943301&s=170667a&w=0&h=8blzipdh9bFJbUtN7Nr4tbgwqnSLXl7icNf2IQp6wO0=" alt="Card image cap" width="70%" height="70%">
    <div class="card-body">
    <h5 class="card-title">TITLE :' . $blog->title . '</h5>
    <p class="card-text">DESCRIPTION :' . $blog->content . '</p>
    <form action="view?bearer='.$token.'" method="POST" >
      <button class="btn bg-dark text-muted" name="view" value="' . $blog->blog_id . '">View Blog</button>
    </form>';
        if ($blog->blog_id == $id) {
            echo ' <form action="../edit/index" method="POST">
        <button type="submit" class="btn bg-primary " value="" name="editBlog"  >EDIT</button>
        </form>';
        }
        echo ' </div>
  </div>
</div>
';
    }
} else {
    echo 'nothing uploaded yet';
}

?>
</div>
</div>