<form action="write" method="POST">
    <div class="container m-5 p-5" >
    <div class="form-group">
        <label >Title</label>
        <input type="text" class="form-control" name="title">
    </div>
    <div class="form-group">
        <label>File</label>
        <input type="file" name="file" class="form-control">
    </div>
    <div class="form-group">
        <label>Content</label>
        <textarea class="form-control" name="content"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</div>
</form>