<?php
// if(isset($_POST['edit'])){
//     echo 'naman';
// }

if (count($value) > 0) {
    echo '<div class="container px-4 px-lg-5 mt-5" id="main">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 ">';
    foreach ($value as $blog) {
        echo '<div class="col mb-5" >
    <div class="card" style="width: 15rem;">
    <img class="card-img-top" src="https://media.istockphoto.com/photos/blog-light-bulb-sign-picture-id1331943301?b=1&k=20&m=1331943301&s=170667a&w=0&h=8blzipdh9bFJbUtN7Nr4tbgwqnSLXl7icNf2IQp6wO0=" alt="Card image cap" width="70%" height="70%">
    <div class="card-body">
    <h5 class="card-title">TITLE :' . $blog->title . '</h5>
    <p class="card-text">DESCRIPTION :' . $blog->content . '</p>
    <form action="view?bearer='.$token.'" method="POST" >
    <button class="btn bg-dark text-muted" name="view" value="' . $blog->blog_id . '">View Blog</button>
    </form>
    <form action="../edit/index" method="POST">
    <button type="submit" name="editBlog"  value="' . $blog->blog_id . ',' . $blog->title . ',' . $blog->content . '" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Edit Blog
  </button>
  </form>

   </div>
  </div>
</div>
';
    }
} else {
    echo 'nothing uploaded yet';
}
?>
</div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <input type="text" name="updatedTitle" value="' . $blog->title . '">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="text" name="updatedContent" value="' . $blog->content . '">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<script>
    function naman(id) {
        $.ajax({
            url: "blog/edit",
            type: 'POST',
            data: {
               action: 'edit',
               id: id

            },
            success: function(html) {
                $("#results").append(html);
            }
        });
    }
</script>