<div class="text-center mt-3">
    <h1 class="text-dark">WELCOME TO BLOGIFY</h1>
</div>
<div>
    <p>Blogify is platform which provides you a wide range of blogs of several different fields come and find your suitable feild for not just reading purpose but allso for the writing purpose as well the worlds awaits your thoughts come and express your view which can be useful for others as well </p>
    <P>With the correct database parameters, our model is ready to interact with the rest of the application so we can save the user’s input. First, let’s take a moment and create a view for SignupController::registerAction() that will display a message letting the user know the outcome of the save operation.</P>
    <h4>What are u waiting for?</h4>
    <h6 class="mx-5">just get started</h6>
</div>
<a href="signup/index" class="btn btn-dark text-lght m-3 px-5" >Get Started</a>

